apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-repair-app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: car-repair-app-secretsmanager
    kind: SecretStore
  target:
    name: car-repair-app-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ConnectionStrings__DefaultConnection: "Host={{ .db_host }};Port={{ .db_port }};Database={{ .db_name }};Username={{ .db_username }};Password={{ .db_password }};Pooling=true;"
        JwtSettings__SecretKey: "{{ .jwt_secret_key }}"
        NEW_RELIC_LICENSE_KEY: "{{ .newrelic_license_key }}"
        SmtpSettings__Username: "{{ .smtp_username }}"
        SmtpSettings__Password: "{{ .smtp_password }}"
  data:
    - secretKey: db_username
      remoteRef:
        key: car-repair/dev/database
        property: username
    - secretKey: db_password
      remoteRef:
        key: car-repair/dev/database
        property: password
    - secretKey: db_host
      remoteRef:
        key: car-repair/dev/database
        property: host
    - secretKey: db_port
      remoteRef:
        key: car-repair/dev/database
        property: port
    - secretKey: db_name
      remoteRef:
        key: car-repair/dev/database
        property: database
    - secretKey: jwt_secret_key
      remoteRef:
        key: car-repair/dev/jwt
        property: secretKey
    - secretKey: newrelic_license_key
      remoteRef:
        key: car-repair/dev/newrelic
        property: licenseKey
    - secretKey: smtp_username
      remoteRef:
        key: car-repair/dev/smtp
        property: username
    - secretKey: smtp_password
      remoteRef:
        key: car-repair/dev/smtp
        property: password
