apiVersion: v1
kind: Service
metadata:
  name: car-repair-shop-api
  namespace: ${namespace}
  labels:
    app: car-repair-shop-api
spec:
  selector:
    app: car-repair-shop-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
