apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-repair-app-secrets
spec:
  data:
    - secretKey: db_username
      remoteRef:
        key: car-repair/prod/database
        property: username
    - secretKey: db_password
      remoteRef:
        key: car-repair/prod/database
        property: password
    - secretKey: db_host
      remoteRef:
        key: car-repair/prod/database
        property: host
    - secretKey: db_port
      remoteRef:
        key: car-repair/prod/database
        property: port
    - secretKey: db_name
      remoteRef:
        key: car-repair/prod/database
        property: database
    - secretKey: jwt_secret_key
      remoteRef:
        key: car-repair/prod/jwt
        property: secretKey
    - secretKey: newrelic_license_key
      remoteRef:
        key: car-repair/prod/newrelic
        property: licenseKey
    - secretKey: smtp_username
      remoteRef:
        key: car-repair/prod/smtp
        property: username
    - secretKey: smtp_password
      remoteRef:
        key: car-repair/prod/smtp
        property: password
