apiVersion: v1
kind: ConfigMap
metadata:
  name: car-repair-app-config
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  NEW_RELIC_APP_NAME: "car-repair-app-hml"
  NEW_RELIC_LABELS: "project:car-repair-shop;environment:hml"
  AuthLambda__BaseUrl: "https://replace-with-hml-auth-gateway.example.com"
  SmtpSettings__Host: "replace-with-hml-smtp-host"
  AppSettings__BaseUrl: "https://hml.car-repair.local"
