apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/workload

images:
  - name: car-repair-app
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/car-repair-dev/car-repair-app
    newTag: dev-placeholder
