apiVersion: v1
kind: ConfigMap
metadata:
  name: car-repair-app-config
  namespace: ${namespace}
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "8080"

  JwtSettings__Issuer: "${jwt_issuer}"
  JwtSettings__Audience: "${jwt_audience}"
  JwtSettings__ExpirationMinutes: "${jwt_expiration_minutes}"

  JwtSecretProvider__SecretName: "${jwt_secret_manager_secret_id}"
  JwtSecretProvider__Region: "${aws_region}"

  AppSettings__BaseUrl: "${app_base_url}"
