apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: car-repair-app-secrets
  namespace: ${namespace}
spec:
  refreshInterval: ${external_secret_refresh_interval}
  secretStoreRef:
    name: car-repair-app-secretsmanager
    kind: SecretStore
  target:
    name: car-repair-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JwtSettings__SecretKey
      remoteRef:
        key: ${jwt_secret_manager_secret_id}
        property: secretKey
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        key: ${postgres_connection_secret_id}
        property: connectionString
    - secretKey: SmtpSettings__Host
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: host
    - secretKey: SmtpSettings__Port
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: port
    - secretKey: SmtpSettings__UseSsl
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: useSsl
    - secretKey: SmtpSettings__Username
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: username
    - secretKey: SmtpSettings__Password
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: password
    - secretKey: SmtpSettings__FromEmail
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: fromEmail
    - secretKey: SmtpSettings__FromName
      remoteRef:
        key: ${smtp_settings_secret_id}
        property: fromName
