apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: car-repair-app-secretsmanager
  namespace: ${namespace}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${aws_region}
      auth:
        jwt:
          serviceAccountRef:
            name: car-repair-app-api
