apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-jwt-credential-car-repair-auth
spec:
  data:
    - secretKey: jwt_secret_key
      remoteRef:
        key: car-repair/hml/jwt
        property: secretKey
